spring.application.name=apiUsers

# --- CONFIGURA??ES DE CONEX?O (DATASOURCE) ---

# Define onde o banco est?. 'mem:testdb' significa que o banco rodar? na MEM?RIA RAM (? vol?til)
spring.datasource.url=jdbc:h2:mem:testdb

# O driver espec?fico que o Java usa para conversar com o H2
spring.datasource.driverClassName=org.h2.Driver

# Usu?rio padr?o do H2 (sa = System Administrator)
spring.datasource.username=sa

# Senha padr?o (em branco)
spring.datasource.password=

# --- CONFIGURA??ES DO JPA / HIBERNATE ---
# Diz ao Hibernate para usar a "gram?tica" (dialeto) espec?fica do H2 ao gerar SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# A M?GICA: 'update' faz o Hibernate criar ou alterar as tabelas no banco
# automaticamente baseando-se nas suas classes Java (@Entity)
spring.jpa.hibernate.ddl-auto=update

# --- CONFIGURA??ES DO CONSOLE VISUAL ---
# Habilita uma interface gr?fica no navegador para voc? ver o banco de dados
spring.h2.console.enabled=true

# O endere?o para acessar o console (ex: localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Adicione isso (troque pelo seu segredo real)
jwt.secret=sua-chave-secreta-aqui-com-pelo-menos-32-caracteres